### ISSUE TITLE
wrong display

### ISSUE THREAD

**Issue by wyf9661** [manjaro-arm/opi5-plus-images#1]
I install the Dec 25 opi5-plus image and find can not display well.
![img_v3_026o_2f20ec3c-d695-4839-9a35-9979f768c22g](https://github.com/manjaro-arm/opi5-plus-images/assets/122584107/392e32d4-73cc-4cad-960a-231ace0fcdf3)

**Comment by spikerguy** [comment]
Yes HDMI was not working well in test kernels.

Hopefully it should be better from todays images, if it works :D
