### ISSUE TITLE
Unable to boot from emmc ？

### ISSUE THREAD

**Issue by GitProPlusMaxUltra** [manjaro-arm/opi5-plus-images#8]
img：Manjaro-ARM-minimal-opi5-plus-20240311.img.xz
I use the official tool to brush write to emmc and it fails to startup 😢

**Comment by spikerguy** [comment]
This image is not to be used with RKdevelop flashing tool.

It have to be flashed directly using etcher or dd, flashing unstable image to emmc is not recommended.

**Comment by GitProPlusMaxUltra** [comment]
> This image is not to be used with RKdevelop flashing tool.
> 
> It have to be flashed directly using etcher or dd, flashing unstable image to emmc is not recommended.

Got it. Thanks for the answer.
